services:
  fastapi:
    build:
      context: ./ChatService
      dockerfile: Dockerfile
    container_name: fastapi_container
    restart: always
    volumes:
      - ./ChatService:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - mongodb
      - weaviate
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  mongodb:
    image: mongo:latest
    container_name: mongodb_container
    restart: always
    volumes:
      - mongo_data:/data/db

  nginx:
    image: nginx:latest
    container_name: nginx_container
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./WebInterface:/usr/share/nginx/html
    depends_on:
      - fastapi

  weaviate:
    image: cr.weaviate.io/semitechnologies/weaviate:1.27.3
    restart: on-failure:0
    volumes:
      - weaviate-data:/var/lib/weaviate
    ports:
    - 8080:8080
    - 50051:50051
    environment:
      QUERY_DEFAULTS_LIMIT: 20
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: "./data"
      CLUSTER_HOSTNAME: 'node1'
      ENABLE_MODULES: text2vec-transformers
      TRANSFORMERS_INFERENCE_API: http://t2v-transformers:8080
      DEFAULT_VECTORIZER_MODULE: text2vec-transformers
  t2v-transformers:
    image: cr.weaviate.io/semitechnologies/transformers-inference:sentence-transformers-multi-qa-MiniLM-L6-cos-v1
    environment:
      ENABLE_CUDA: 0


volumes:
  mongo_data:
  weaviate-data:
