services:
  fastapi:
    build:
      context: ./ChatService
      dockerfile: Dockerfile
    container_name: fastapi_container
    restart: always
    ports:
      - "8000:8000"

  nginx:
    image: nginx:latest
    container_name: nginx_container
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./WebInterface:/usr/share/nginx/html
    depends_on:
      - fastapi
